name: hello-world-pyhton
version: '0.1'
summary: A hello world style python
description: 
  This example python script that says hello to you.
confinement: devmode
base: core22

apps:
  hello-world-ptyhon:
    command: /bin/python3 ./src/hello-world.py

parts:
  hello:
    plugin: python
    source: .