name: hello-world-python # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
architectures:
  - build-on: armhf
    build-for: armhf
version: git # just for humans, typically '1.2+git' or '1.3.2'
summary: Simple hello world snap. # 79 char long summary
description: |
  Simple hello world snap.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots


apps:
  hello-world-python:
    command: bin/helloworld

parts:
  hello-world-python:
    # See 'snapcraft plugins'
    plugin: python
    source: .
    # source: https://github.com/pydaw/hello-ubuntu-core.git/ # Works too
    